### ISSUE TITLE
How to use this EIS code?

### ISSUE THREAD

**Issue by zhimins** [Gcarassai/EIS#1]
Hi 
Could you have more description about this code? I have some EIS data to deal with. I used to use the EC-lab, but it takes too much time.

Thanks much
Zhimin

**Comment by Gcarassai** [comment]
Hi Zhimin,

The code is still very much in progress, so not everything works properly. Anyhow, the MPT_MPR.py file basically reads .mpt files (which are usually where EC-lab data is stored) and converts said files in dataframes. I am trying to make it read .mpr files too, but I'm having some trouble with Galvani package. MPT_MPR.py should then be used as a module to use another script that I am currently working on, which will automatically fit the equivalent circuit to your data.

Thank you for your interest and I hope I'll finish everything soon!
Giulio
